### PR TITLE
Construction page design done

### PR DESCRIPTION
**Pull request by lockround**
check out live page here https://imaginetech-website.surge.sh.
Thanks. :+1:

### CODE REVIEW

**Comment by mortensenm1205** [comment]
We won't accept this yet. Please don't merge.

**Comment by mortensenm1205** [comment]
The review is being difficult. 
So i'll post my change requests here. Please let me know if you don't understand. Sorry for the issues.

**Comment by mortensenm1205** [comment]
`src/components/Home/index.js`

Line 15
Please move `Countdown` within the screens folder. Since we are piecing how this component will look towards the user, that is done in the screens folder.

**Comment by mortensenm1205** [comment]
`src/components/Home/Content.js`

Line 6 & 7 
`Header` will also have to be moved into Screens.

**Comment by mortensenm1205** [comment]
`src/components/Home/Countdown/index.js`

`Countdown` directory needs to be on it's own. Please place this within `src/components` and not nested within Home. 
Whenever we have feature as unique as this, it should be it's own directory.

**Comment by lockround** [comment]
> > I'm sorry but you put `Header` in `components` thats why i didn't move it in screens.
> 
> The idea is that any time you place a component from another folder into another component, that is dealing with how the View will be displayed. All View matters will be handled in the screens, no matter how small the change me be.

sorry, i got it.
Just a min pushing some refactoring.

**Comment by mortensenm1205** [comment]
The rest of the files are not bad! 

Just a heads up, we won't be using the containers just components. They meant to hold the components together so that it can be used later in the screens folder. 

So files like `Footer/index`, `Header/index` and `Home/index` should just hold other components. Make any jsx into it's own component, no matter how small it is, this allows for easier debugging based on whoever picks up the project.

**Comment by lockround** [comment]
> The rest of the files are not bad!
> 
> Just a heads up, we won't be using the containers just components. They meant to hold the components together so that it can be used later in the screens folder.
> 
> So files like `Footer/index`, `Header/index` and `Home/index` should just hold other components. Make any jsx into it's own component, no matter how small it is, this allows for easier debugging based on whoever picks up the project.

Ahh, sorry you are actually right.
thanks 
i'll fix real quick.

**Comment by mortensenm1205** [comment]
@lockround Perfect my dude!!! Again, i'll write up these updates so that they reflect on the style guide. Thanks so much for working with me on this one. lgtm, merged.

**Comment by lockround** [comment]
> @lockround Perfect my dude!!! Again, i'll write up these updates so that they reflect on the style guide. Thanks so much for working with me on this one. lgtm, merged.

Thanks sir. :100:

**Pull request merged**
